site_name: Fear & loathing in Las Marinas
site_author: Dra Katharine Murphy
site_url: https://fearandloathinginlasmarinas.com/
copyright: Copyright &copy; 2025 Dra Katharine Murphy
repo_name: Police statement

theme:
  name: material
  custom_dir: 'overrides'
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/eye
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  language: en
  favicon: content/images/favicon.ico
  logo: content/images/skull.png
  features:
    - search.suggest
    - search.highlight
    - search.share
    #- navigation.instant
    #- navigation.instant.progress
    - navigation.tracking
    - navigation.integration
    #- navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    #- navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.action.edit

nav:
  - Preface: preface.md
  - Dedication: dedication.md
  - Home: 
    - Summary: index.md
  - Timeline:
    - Early years:
      - "2001": timeline/early-years/2001.md
      - "2003": timeline/early-years/2003.md
      - "2005": timeline/early-years/2005.md
      - "2006": timeline/early-years/2006.md
      - "2007": timeline/early-years/2007.md
      - "2008": timeline/early-years/2008.md
      - "2009": timeline/early-years/2009.md
      - "2010": timeline/early-years/2010.md
      - "2011": timeline/early-years/2011.md
      - "2012": timeline/early-years/2012.md
      - "2013": timeline/early-years/2013.md
      - "2014": timeline/early-years/2014.md
      - "2015": timeline/early-years/2015.md
      - "2016": timeline/early-years/2016.md
      - "2020": timeline/early-years/2020.md
      - Interim: timeline/early-years/interim.md
    - "2021":
      - January: timeline/2021/january.md
      - March: timeline/2021/march.md 
      - April: timeline/2021/april.md
      - July: timeline/2021/july.md
      - October: timeline/2021/october.md
      - December: timeline/2021/december.md
    - "2022":
      - February: timeline/2022/february.md
      - March: timeline/2022/march.md
      - June: timeline/2022/june.md
      - July: timeline/2022/july.md
      - September: timeline/2022/september.md
      - October: timeline/2022/october.md
      - November: timeline/2022/november.md
      - December: timeline/2022/december.md
    - "2023":
      - January: timeline/2023/january.md
      - February: timeline/2023/february.md
      - March: timeline/2023/march.md
      - April: timeline/2023/april.md
      - May: timeline/2023/may.md
      - June: timeline/2023/june.md
      - July: timeline/2023/july.md
      - August: timeline/2023/august.md
      - September: timeline/2023/september.md
      - October: timeline/2023/october.md
      - November: timeline/2023/november.md
      - December: timeline/2023/december.md
    - "2024":
      - January: timeline/2024/january.md
      - February: timeline/2024/february.md
      - March:
        - Summary: timeline/2024/march/march.md
        - 1st to 12th: timeline/2024/march/1-12.md
        - 13th to end: timeline/2024/march/13-end.md
      - April: timeline/2024/april.md
      - May: timeline/2024/may.md
      - June: timeline/2024/june.md
      - July: timeline/2024/july.md
      - August: timeline/2024/august.md
      - September: timeline/2024/september.md
      - October: timeline/2024/october.md
      - November: timeline/2024/november.md
      - December: timeline/2024/december.md
    - "2025":
      - January: timeline/2025/january.md
      - February: timeline/2025/february.md
      - March: timeline/2025/march.md
      - April: timeline/2025/april.md
      - May: timeline/2025/may.md
      - June: timeline/2025/june.md
      - July: timeline/2025/july.md
      - August: timeline/2025/august.md
      - September: timeline/2025/september.md
      - October: timeline/2025/october.md
      - November: timeline/2025/november.md
      - December: timeline/2025/december.md
    - "2026":
      - January: timeline/2026/january.md
  - Crimes:
    - Protagonists: 
      - Vidal Sastre Sanchez Hornero: crimes/protagonists/vidal-sastre.md
      - Teachers and staff at the conservatory: crimes/protagonists/domingo-et-al.md
      - Winston May & Nicky: crimes/protagonists/winston-may-and-nicky.md
    - Introduction agents: crimes/introduction-agents.md
    - Poisoning and drugging: crimes/poisoning.md
    - Gaslighting: crimes/gaslighting.md
    - Traditional gang stalking in Spain: crimes/traditional-stalking.md
    - Modern day gang stalking: crimes/modern-stalking.md
    - Hacking: crimes/hacking.md
    - Cyber-stalking: crimes/cyberstalking.md
    - Mass voyeurism: crimes/mass-voyeurism.md
    - Trying to get help: crimes/getting-help.md
    - Honey-trapping: crimes/honeytrap.md
    - Pedophilia: crimes/pedophilia.md
    - Rape porn: crimes/rape-porn.md
  - Evidence:
    - Manipulation techniques: evidence/manipulation.md
    - CCTV: evidence/cctv.md
    - Memes and triggers: evidence/memes-and-triggers.md
    - Screenshots: evidence/screenshots.md
    - Twitter accounts: evidence/twitter-account.md
    - Google searches: evidence/google-searches.md
    - WhatsApps: evidence/whatsapps.md
    - Maybe's: evidence/maybes.md
  - Personal experience: 
    - Health: personal/health.md
    - Expenses: personal/expenses.md
    - Hacking: personal/hacking.md
  - Conclusion:
    - Theories: conclusion/theories.md
    - Justice: conclusion/a-proper-ending.md
  - The novel:
    - Fear and loathing in Las Marinas, DÃ©nia: the-novel/book-cover.md
    - Optional book covers: the-novel/optional-covers.md


extra:
  social:
    - icon: fontawesome/brands/x-twitter
      name: 1FRGVN on X
      link: https://x.com/1FRGVN
    - icon: fontawesome/brands/facebook
      name: 1FRGVN on Facebook
      link: https://www.facebook.com/profile.php?id=61561067270886
    - icon: fontawesome/brands/instagram
      name: 1FRGVN on Instagram
      link: https://www.instagram.com/jacquelinachardwood/
    - icon: fontawesome/brands/threads
      name: 1FRGVN on Substack
      link: https://fearandloathinginlasmarinas.substack.com/
    - icon: fontawesome/brands/github
      name: 1FRGVN on GitHub
      link: https://github.com/kailash-manasarovar/statement

      

extra_css:
  - extra.css
  - https://fonts.googleapis.com/icon?family=Material+Icons
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Link to this section
      toc_depth: 4
  - codehilite
  - markdown_include.include:
      base_path: docs
  - admonition
  - footnotes
  - def_list
  - attr_list
  - abbr
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
  - meta
  - smarty

plugins:
  - search
  - open-in-new-tab
  #- git-revision-date-localized
  #- social:
  #    cards_layout_options:
  #      background_image: \content\images\the-novel\cover-2.webp
  #      background_color: transparent

validation:
  absolute_links: warn
  anchors: warn

